apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-prometheus-avalanche.fullname" . }}
  labels:
    app: {{ include "helm-prometheus-avalanche.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "helm-prometheus-avalanche.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "helm-prometheus-avalanche.name" . }}
    spec:
      containers:
        - name: {{ include "helm-prometheus-avalanche.name" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          env:
            - name: HELLO_ENV
              value: "{{ .Values.helloEnv }}"
          args:
          {{- range .Values.arguments }}
            - {{ . | quote }}
          {{- end }}
            - "--port={{ .Values.service.port }}"
          ports:
            - name: http-metrics
              containerPort: {{ .Values.service.port }}
              protocol: TCP
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
