apiVersion: v1
kind: Pod
metadata:
  name: netshoot-{{ .Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  hostNetwork: {{ .Values.hostNetwork }}
  hostPID: {{ .Values.hostPID }}
  containers:
  - name: netshoot
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    command: ["sleep"]
    args: ["infinity"]
    securityContext:
      privileged: {{ .Values.privileged }}
  restartPolicy: Always
